server:
  port: 9192

spring:
  datasource:
    username: root
    password: tVw@20041023
    url: jdbc:mysql://localhost:3306/osianViwe_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
    max-file-size: 5MB
    max-request-size: 5MB
    file-size-threshold: 2KB

  security:
    jwt:
      secret: EQPTdCNBKkY24Z9aTdF9CSNTU9ZqkOPt5l65uyMSuOM
      expiration-time: 3600000




